### PR TITLE
support adding new resources with PUT method and conformance tests report

### PR DESCRIPTION
**Pull request by m-alreeni**
LDP-service was tested with W3C testsuite and passed all automated conformance tests for all groups (MUST, SHOULD, MAY). all manual tests have been skipped (hardcoded in suite to skipp them) and need to be tested manually.
the tests were made with :
- default configuration (passing handler with value null to LDPHelper or default BasicContainerHandler) . 
- with special configuration for DOM

We had got the same result as in the conformance report.

### CODE REVIEW

**Comment by kenwenzel** [comment]
This is really good work - thank you!
I have to test this locally because Travis fails for some reason.

**Comment by m-alreeni** [comment]
> @m-alreeni This means we are finally fully LDP-compatible?

yes but some tests could not be automated (for example most of PATCH test cases, therefore i have tested these locally and manually). We can later enrich the suite with such tests to prove that the  skipped tests pass too

**Review by kenwenzel — CHANGES_REQUESTED** [review]
Is it possible to leave out the file `bundles/web/net.enilink.platform.ldp/ldp-testsuite-execution-report.html`? It seems to be rather large.
Could it be replaced with a short Markdown notice or is it even possible to generate the file as part of the build process?

**Comment by m-alreeni** [comment]
> Is it possible to leave out the file `bundles/web/net.enilink.platform.ldp/ldp-testsuite-execution-report.html`? It seems to be rather large. Could it be replaced with a short Markdown notice or is it even possible to generate the file as part of the build process?

@kenwenzel 
done

**Pull request merged**
